Repository yankaindustries/mc-components, pull requests merged in 2018-08, with the labels that each got.

#130 Feature/easier imports
  README.md
  docs/PROPOSAL.md
  package.json
  src/styles/index.scss
Labels: enhancement

#129 Fixing issue with PropsTable not reading more complex prop types
  src/components/TextArea/index.js
  src/components/Tile/__snapshots__/index.stories.storyshot
  src/components/TileVideo/__snapshots__/index.stories.storyshot
  src/components/TileVideo/index.js
  src/utils/PropsTable.js
Labels: bug

#139 Updating type styles
  src/components/Foundation/Type/index.stories.js
  src/styles/base/_variables.scss
  src/styles/typography/_typography.scss
  src/styles/typography/base.scss
  src/styles/typography/modifiers.scss
Labels: maintenance

#150 Add "inverted" text modifier
  src/styles/components/_class-card.scss
  src/styles/components/_footer.scss
  src/styles/components/_icons.scss
  src/styles/components/_navbar-menu.scss
  src/styles/components/_tile.scss
  src/styles/components/_video-player.scss
  src/styles/components/buttons/_button--types.scss
  src/styles/release-candidate/components/_navbar-menu.scss
  src/styles/typography/base.scss
  src/styles/typography/modifiers.scss
Labels: enhancement

#168 Remove font
  README.md
  src/styles/typography/_typography.scss
  src/styles/typography/fonts.scss
Labels: maintenance

#187 Define color variables for body background and text colors
  .storybook/_upside-down.scss
  src/styles/base/_variables.scss
  src/styles/typography/base.scss
Labels: enhancement

#190 Consolidate heading type styles
  src/foundation/type/index.stories.js
  src/styles/typography/base.scss
  src/styles/typography/modifiers.scss
Labels: maintenance
