Repository yankaindustries/mc-components, pull requests merged in 2018-07, with the labels that each got.

#58 Update readme
  README.md
Labels: enhancement

#57 General cleanup: Remove npm lock, improve scss linter error handling in console, remove unused scss variables
  .gitignore
  package-lock.json
  package.json
  src/styles/base/_variables.scss
  src/styles/components/_badge.scss
  src/styles/components/_header.scss
  src/styles/components/_mobile-nav-button.scss
  src/styles/components/_navbar-menu.scss
  src/styles/components/_overlay-check.scss
  src/styles/components/_rounded-box.scss
  src/styles/components/buttons/_c-button.scss
  src/styles/components/forms/_radio-input.scss
  src/styles/components/modal/_modal-content.scss
  src/styles/components/modal/_modal-header.scss
  src/styles/mixins/_ratios.scss
  src/styles/typography/_mc-component-typography.scss
  src/styles/typography/base.scss
Labels: enhancement

#59 Add minimal footer
  src/assets/logo-minimal.svg
  src/components/Badge/__snapshots__/index.stories.storyshot
  src/components/Button/__snapshots__/index.stories.storyshot
  src/components/Carousel/__snapshots__/index.stories.storyshot
  src/components/CheckTile/__snapshots__/index.stories.storyshot
  src/components/Footer/__snapshots__/index.stories.storyshot
  src/components/Footer/index.js
  src/components/Footer/index.stories.js
  src/components/GridExample/__snapshots__/index.stories.storyshot
  src/components/HeaderLoggedIn/__snapshots__/index.stories.storyshot
  src/components/ImageTile/__snapshots__/index.stories.storyshot
  src/components/Input/__snapshots__/index.stories.storyshot
  src/components/Modal/__snapshots__/index.stories.storyshot
  src/components/RadioInput/__snapshots__/index.stories.storyshot
  src/components/RoundedBox/__snapshots__/index.stories.storyshot
  src/components/TextArea/__snapshots__/index.stories.storyshot
  src/components/VideoPlayer/__snapshots__/index.stories.storyshot
Labels: enhancement

#61 Remove last references to npm, add yarn start script
  README.md
  package.json
  yarn.lock
Labels: enhancement

#63 Cleaning up styles, fixing missing mixin bp variable
  src/styles/base/_variables.scss
  src/styles/components/buttons/_button--types.scss
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_buttons.scss
  src/styles/components/buttons/default.scss
  src/styles/components/buttons/link.scss
  src/styles/components/buttons/secondary.scss
  src/styles/components/forms/_input.scss
  src/styles/components/forms/_radio-input.scss
  src/styles/components/modal/_modal-content.scss
  src/styles/typography/_mc-component-typography.scss
Labels: bug, enhancement

#64 Adding a script for versioning
  package.json
Labels: enhancement

#68 Preparation for better versioning
  .gitignore
  README.md
  package.json
Labels: enhancement

#69 Fix missing variable
  src/styles/components/_class-card.scss
  src/styles/release-candidate/components/_badge.scss
  src/styles/release-candidate/components/_header.scss
  src/styles/release-candidate/components/_mobile-nav-button.scss
  src/styles/release-candidate/components/_navbar-menu.scss
Labels: bug

#98 Flip order for input variables
  src/styles/components/forms/_input.scss
Labels: bug

#108 Removing unused legacy icons
  src/styles/components/_components.scss
  src/styles/components/_icons.scss
  src/styles/icons/arrow.svg
  src/styles/icons/close.svg
  src/styles/icons/hamburger.svg
  src/styles/icons/input-checkmark.svg
  src/styles/icons/loader.svg
  src/styles/icons/lock.svg
  src/styles/icons/mute.svg
  src/styles/icons/sound.svg
Labels: maintenance

#113 Tech debt: button cleanup
  package.json
  src/styles/components/buttons/_button--types.scss
  src/styles/components/buttons/_button.scss
Labels: maintenance
