Repository yankaindustries/mc-components, pull requests merged in 2018-11, with the labels that each got.

#274 Input: fix label class
  src/components/Input/index.js
Labels: bug, safe to merge

#276 added missing bootstrap fn for generating mc-text--center classes
  src/styles/base/_functions.scss
Labels: bug, safe to merge

#278 adding typography tests
  src/foundation/type/beta.stories.js
  src/styles/typography/_base.scss
  src/styles/typography/_beta.scss
  src/styles/typography/_modifiers.scss
  src/styles/typography/_typography.scss
Labels: enhancement

#279 Scope beta stuff to beta pages
  src/styles/typography/_base.scss
  src/styles/typography/_beta.scss
Labels: bug

#280 Final button updates
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/playground/home/index.stories.js
  src/styles/base/_variables.scss
  src/styles/components/buttons/_button--inverted.scss
  src/styles/components/buttons/_button--types.scss
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_buttons.scss
Labels: enhancement

#286 Updating underline styles for button link types
  src/styles/components/buttons/_button--types.scss
Labels: enhancement, maintenance

#294 Adding 9 by 16 tile ratios
  src/components/ImageTile/index.js
  src/components/Tile/index.js
  src/styles/components/_tile.scss
Labels: enhancement

#295 Adding dots to carousel
  src/components/Carousel/index.stories.js
  src/styles/components/_carousel.scss
  src/styles/components/_tile.scss
Labels: enhancement

#299 Temporarily removing fadeEdges until needed, implementation is flawed
  src/components/Carousel/index.js
  src/components/Carousel/index.stories.js
  src/styles/components/_carousel.scss
Labels: bug

#300 Fixing tertiary color regression
  src/styles/base/_variables.scss
  src/styles/components/buttons/_button--types.scss
Labels: bug

#306 Adding 21x9 tile aspect ratio
  src/components/Tile/index.js
  src/components/Tile/index.stories.js
  src/styles/components/_tile.scss
Labels: enhancement

#313 Adding new arrow styles per design
  src/styles/components/_carousel.scss
Labels: enhancement
