Repository yankaindustries/mc-components, pull requests merged in 2018-09, with the labels that each got.

#199 Tile improvements
  src/components/AnimationHandler/index.stories.js
  src/components/Background/index.js
  src/components/Carousel/index.stories.js
  src/components/Tile/index.stories.js
  src/components/TileCaption/index.js
  src/components/TileCaption/index.stories.js
  src/components/TileCheck/index.stories.js
  src/components/TileImage/index.js
  src/components/TileImage/index.stories.js
  src/components/TileOverlay/index.stories.js
  src/styles/components/_background.scss
  src/styles/components/_tile.scss
  src/styles/typography/modifiers.scss
Labels: enhancement, update component

#204 Changes to container max-widths
  .storybook/_upside-down.scss
  src/foundation/variables/index.stories.js
  src/styles/base/_variables.scss
  src/styles/components/_carousel.scss
  src/styles/components/_section.scss
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: enhancement

#205 Updating variables in storybook to reflect current breakpoint variables
  src/foundation/variables/index.stories.js
Labels: maintenance

#206 Updating breakpoints
  .storybook/_upside-down.scss
  src/components/Tile/index.stories.js
  src/components/TileCaption/index.stories.js
  src/components/TileCheck/index.stories.js
  src/components/TileImage/index.stories.js
  src/components/TileOverlay/index.stories.js
  src/components/TileVideo/index.stories.js
  src/foundation/variables/index.stories.js
  src/styles/base/_variables.scss
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: enhancement

#208 Support video player screens in full screen mode
  src/components/VideoPlayer/index.js
  src/components/VideoPlayerPortalScreen/index.js
  src/components/VideoPlayerScreen/index.js
Labels: enhancement

#211 Updating color variables
  src/styles/base/_variables.scss
  src/styles/typography/base.scss
Labels: maintenance

#216 Legacy classnames
  src/styles/components/_tile.scss
Labels: maintenance
