Repository yankaindustries/mc-components, pull requests merged in 2018-10, with the labels that each got.

#219 Update footer grid
  src/assets/icons/logo.svg
  src/assets/icons/ssl-badge.svg
  src/components/Footer/index.js
  src/components/Icons/Logo.js
  src/components/Icons/SslBadge.js
  src/styles/base/_variables.scss
  src/styles/components/_footer.scss
Labels: maintenance

#223 Fix for rails pipeline css consumption issues
  src/styles/libraries/_libraries.scss
  src/styles/libraries/bootstrap-grid/_functions.scss
  src/styles/libraries/bootstrap-grid/_grid.scss
  src/styles/libraries/bootstrap-grid/_variables.scss
  src/styles/libraries/bootstrap-grid/bootstrap-grid.scss
  src/styles/libraries/bootstrap-grid/mixins/_breakpoints.scss
  src/styles/libraries/bootstrap-grid/mixins/_grid-framework.scss
  src/styles/libraries/bootstrap-grid/mixins/_grid.scss
  src/styles/libraries/bootstrap-grid/utilities/_display.scss
  src/styles/libraries/bootstrap-grid/utilities/_flex.scss
  src/styles/libraries/slick-carousel/slick.scss
Labels: maintenance

#221 Form elements
  .storybook/_upside-down.scss
  package.json
  src/assets/icons/arrow.svg
  src/assets/icons/lock.svg
  src/assets/icons/magnifying-glass.svg
  src/components/Checkbox/index.js
  src/components/CheckboxField/index.js
  src/components/CheckboxField/index.stories.js
  src/components/Forms/index.stories.js
  src/components/Icons/Arrow.js
  src/components/Icons/Lock.js
  src/components/Icons/MagnifyingGlass.js
  src/components/Input/index.js
  src/components/Input/index.stories.js
  src/components/InputField/index.js
  src/components/InputField/index.stories.js
  src/components/Legacy/Input/index.js
  src/components/Legacy/RadioInput/index.js
  src/components/Legacy/TextArea/index.js
  src/components/Radio/index.js
  src/components/RadioField/index.js
  src/components/RadioField/index.stories.js
  src/components/RadioInput/index.stories.js
  src/components/TextArea/index.js
  src/components/TextArea/index.stories.js
  src/components/index.js
  src/styles/base/_variables.scss
  src/styles/components/_rounded-box.scss
  src/styles/components/forms/_forms.scss
  src/styles/components/forms/_input.scss
  src/styles/components/forms/_structure.scss
  src/styles/components/forms/checkbox/_default.scss
  src/styles/components/forms/checkbox/_modifiers.scss
  src/styles/components/forms/checkbox/_states.scss
  src/styles/components/forms/checkbox/checkbox.scss
  src/styles/components/forms/input/_default.scss
  src/styles/components/forms/input/_input.scss
  src/styles/components/forms/input/_modifiers.scss
  src/styles/components/forms/radio/_default.scss
  src/styles/components/forms/radio/_modifiers.scss
  src/styles/components/forms/radio/_radio.scss
  src/styles/components/forms/radio/_states.scss
  src/styles/components/forms/textarea/_default.scss
  src/styles/components/forms/textarea/_modifiers.scss
  src/styles/components/forms/textarea/_textarea.scss
  yarn.lock
Labels: enhancement, new component

#226 Reduce wildcard specificity of column selector
  src/styles/libraries/_libraries.scss
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: bug

#222 videoJS buffers bug
  src/components/VideoPlayer/index.js
Labels: bug, enhancement, safe to merge

#230 `TileVideo` improvements
  src/components/Tile/index.stories.js
  src/components/TileVideo/index.js
  src/styles/components/_tile.scss
Labels: enhancement

#235 Remove unused --light style and readd --x-light to documentation
  src/components/AnimationHandler/index.stories.js
  src/components/Carousel/index.stories.js
  src/components/Tile/index.stories.js
  src/foundation/type/index.stories.js
  src/playground/home/index.stories.js
  src/styles/typography/modifiers.scss
Labels: maintenance, safe to merge

#238 Add no-gutters-vertical class
  src/foundation/grid/index.stories.js
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: enhancement

#237 Updating gutter widths after experimenting with real implementation
  src/styles/base/_variables.scss
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: enhancement

#236 Add hex values to documentation in variables section
  .storybook/_upside-down.scss
  src/foundation/variables/index.stories.js
Labels: enhancement

#245 Stripping existing modal implementation out
  src/components/Modal/index.js
  src/components/Modal/index.stories.js
  src/components/ModalHeader/index.js
  src/components/ModalPortal/index.js
  src/components/index.js
  src/styles/components/_components.scss
  src/styles/components/modal/_modal-content.scss
  src/styles/components/modal/_modal-header.scss
  src/styles/components/modal/_modal.scss
Labels: maintenance

#241 Building new <Modal /> component
  src/components/Modal/index.js
  src/components/Modal/index.stories.js
  src/components/ModalContent/index.js
  src/styles/components/_modal.scss
Labels: enhancement

#250 Adding sitemap link to footer
  src/components/Footer/index.js
  src/styles/components/_footer.scss
Labels: enhancement

#251 Add story example for disabled buttons
  src/components/Button/index.stories.js
  src/styles/components/buttons/_button.scss
Labels: enhancement
