Repository yankaindustries/mc-components, pull requests merged in 2019-01, with the labels that each got.

#332 Add highlightOnActive and highlightOnHover props to carousel component
  src/components/Carousel/index.js
  src/components/Carousel/index.stories.js
  src/styles/components/_components.scss
  src/styles/components/carousel/_base.scss
  src/styles/components/carousel/_carousel.scss
  src/styles/components/carousel/_modifiers.scss
Labels: enhancement

#333 Adding better handling for form input states like hover and error
  src/styles/components/forms/input/_default.scss
  src/styles/components/forms/input/_modifiers.scss
Labels: bug

#335 Remove abstraction for button colors so colors are more obvious
  src/styles/components/buttons/_button--types.scss
Labels: enhancement

#338 Update copyright year on footer
  src/components/Footer/index.js
Labels: enhancement, safe to merge

#344 Tertiary button updates
  src/styles/base/_variables.scss
  src/styles/components/buttons/_button--inverted.scss
  src/styles/components/buttons/_button--types.scss
Labels: enhancement

#341 Updating button examples with icons
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/styles/components/buttons/_button.scss
Labels: enhancement

#345 Add hinted text modifier styles
  src/foundation/introduction/scale.stories.js
  src/foundation/typography/modifiers.stories.js
  src/styles/typography/_modifiers.scss
Labels: enhancement

#346 Adding helpers to limit total lines of text
  src/foundation/typography/modifiers.stories.js
  src/styles/base/_variables.scss
  src/styles/typography/_base.scss
  src/styles/typography/_modifiers.scss
Labels: enhancement

#348 Fix label alignment for textareas
  src/styles/components/forms/textarea/_default.scss
Labels: bug

#352 Add hinted modifier button to documentation
  src/foundation/typography/summary.stories.js
Labels: enhancement

#353 Remove the facebook and twitter custom link colors
  src/foundation/typography/colors.stories.js
  src/foundation/typography/index.stories.js
  src/styles/typography/_modifiers.scss
Labels: maintenance
