Repository yankaindustries/mc-components, pull requests merged in 2019-06, with the labels that each got.

#500 removing remnants of header and footer, fixing accordion timing
  src/components/Footer/index.js
  src/components/index.js
  src/playground/home/index.stories.js
  src/styles/animation/_animation.scss
  src/styles/components/_components.scss
  src/styles/components/_footer.scss
Labels: maintenance

#501 Removing the rest of the things
  src/components/NavBarMenu/index.js
  src/components/NavBarMenuItem/index.js
  src/components/index.js
  src/styles/components/_components.scss
  src/styles/components/_mobile-nav-button.scss
  src/styles/components/_navbar-menu.scss
Labels: maintenance

#502 Expanding line helper support
  src/foundation/typography/modifiers.stories.js
  src/styles/typography/_modifiers.scss
Labels: enhancement

#504 Adding other arrow directions
  src/assets/icons/arrow-down.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-top.svg
  src/components/Icons/ArrowDown.js
  src/components/Icons/ArrowLeft.js
  src/components/Icons/ArrowTop.js
  src/components/Icons/icons.js
Labels: maintenance

#506 Accordion/animation improvements
  src/components/Accordion/index.js
  src/components/AnimationHandler/index.js
  src/playground/lihp/index.stories.js
  src/styles/animation/_animation.scss
  src/styles/components/_accordion.scss
Labels: bug, enhancement

#507 Adding 'link' and 'sms' as Icon kinds
  src/assets/icons/link.svg
  src/assets/icons/sms.svg
  src/components/Icons/Link.js
  src/components/Icons/Sms.js
  src/components/Icons/icons.js
Labels: enhancement

#508 Add support for clamping line helpers
  src/styles/typography/_modifiers.scss
Labels: enhancement

#511 Fix bug related to build process for hidden files in assets folder
  build/assets.js
Labels: bug

#510 adding helper directly to responsive handler
  src/components/ResponsiveHandler/index.js
  src/components/ResponsiveHandler/index.stories.js
  src/components/helpers.js
Labels: enhancement

#513 Modal - Sizes
  src/components/Input/index.js
  src/components/Modal/index.js
  src/components/Modal/index.stories.js
  src/components/ModalContent/index.js
  src/styles/components/_modal.scss
  src/styles/components/_tile.scss
  src/utils/instructor-grid.png
  src/utils/tv-hero.png
Labels: enhancement

#519 Adding Share and List icon
  src/assets/icons/list.svg
  src/assets/icons/share.svg
  src/components/Icons/List.js
  src/components/Icons/Share.js
  src/components/Icons/icons.js
Labels: new component

#518 Syncing separator to 30% opacity per design meeting
  .storybook/_upside-down.scss
  src/styles/components/_separator.scss
Labels: maintenance

#517 Changing opacity helper naming
  src/components/AnimationHandler/index.stories.js
  src/components/Background/index.stories.js
  src/components/Carousel/index.stories.js
  src/components/CarouselConnector/index.stories.js
  src/components/Dropdown/index.stories.js
  src/components/FormGroup/index.js
  src/components/HoverHandler/index.stories.js
  src/components/Icons/index.stories.js
  src/components/Modal/index.stories.js
  src/components/ResponsiveHandler/index.stories.js
  src/components/Tile/index.stories.js
  src/components/ToggleHandler/index.stories.js
  src/components/VideoPlayer/index.stories.js
  src/foundation/grid/index.stories.js
  src/foundation/scale/index.stories.js
  src/foundation/spacing/index.stories.js
  src/foundation/typography/modifiers.stories.js
  src/foundation/typography/summary.stories.js
  src/foundation/utilities/index.stories.js
  src/foundation/utilities/opacity.stories.js
  src/foundation/variables/index.stories.js
  src/playground/home/index.stories.js
  src/playground/lihp/index.stories.js
  src/styles/helpers/_helpers.scss
  src/styles/helpers/_opacity.scss
  src/styles/typography/_modifiers.scss
  src/utils/DocHeader.js
  src/utils/PropExample.js
Labels: maintenance
