Repository yankaindustries/mc-components, pull requests merged in 2019-03, with the labels that each got.

#381 Improving label, error, and help text rendering when content is large
  src/components/FormGroup/index.js
  src/components/Forms/index.stories.js
  src/styles/libraries/bootstrap-overrides/_grid.scss
Labels: enhancement

#386 Prevent Modal backdrop click through
  src/components/Modal/index.js
Labels: enhancement

#390 Updating bootstrap
  package.json
  yarn.lock
Labels: maintenance

#391 Fix bug on animation handler button examples
  src/components/AnimationHandler/index.stories.js
Labels: bug

#404 Updating body letter spacing per design request
  src/styles/typography/_base.scss
Labels: maintenance

#403 Fix overflow on body for iOS devices caused by overflowing tile rows
  src/styles/body/_body.scss
Labels: bug

#402 Updating button padding to new design specs
  src/styles/components/buttons/_button--types.scss
  src/styles/components/buttons/_button.scss
Labels: maintenance

#414 Updating carousel arrow implementation
  src/styles/components/carousel/_base.scss
Labels: enhancement

#413 Adding documentation for display helper utilities
  src/foundation/utilities/display.stories.js
  src/foundation/utilities/index.stories.js
Labels: maintenance

#417 Fix double body scrollbar
  src/styles/body/_body.scss
Labels: bug

#420 Remove mobile nav button
  src/components/MobileNavButton/index.js
  src/components/index.js
Labels: maintenance

#419 Adding higher z-index for hovered animated items
  src/styles/animation/_animation.scss
Labels: bug

#418 Accordion: change hover styles so space-filling children don't trigger hover states
  src/components/Accordion/index.js
  src/components/Accordion/index.stories.js
  src/components/HoverHandler/index.js
  src/playground/lihp/index.stories.js
Labels: enhancement

#423 Update incorrect documentation terminology
  src/foundation/scale/scale.stories.js
Labels: enhancement

#431 Updating css selector to fix carousel highlight bugs
  src/styles/components/carousel/_modifiers.scss
Labels: bug
