Repository yankaindustries/mc-components, pull requests merged in 2019-04, with the labels that each got.

#436 Adding documentation for carousel properties
  src/components/Carousel/index.js
  src/components/Carousel/index.stories.js
Labels: enhancement

#438 Adding documentation for all aspect ratios
  src/components/Accordion/index.stories.js
  src/components/Tile/index.stories.js
Labels: enhancement

#441 Add documentation for select fields and clean up disabled form states
  src/components/Select/index.js
  src/components/SelectField/index.stories.js
  src/styles/components/forms/_checkbox.scss
  src/styles/components/forms/_element.scss
Labels: maintenance

#456 allowing autoplay for safari if the video is muted
  src/components/VideoPlayer/index.js
Labels: bug

#455 documentation - adding github src links
  .storybook/_upside-down.scss
  .storybook/config.js
  src/components/Accordion/index.stories.js
  src/components/AnimationHandler/index.stories.js
  src/components/Background/index.stories.js
  src/components/Button/index.stories.js
  src/components/Carousel/index.stories.js
  src/components/CarouselConnector/index.stories.js
  src/components/CheckboxField/index.stories.js
  src/components/Forms/index.stories.js
  src/components/HoverHandler/index.stories.js
  src/components/InputField/index.stories.js
  src/components/Modal/index.stories.js
  src/components/RadioField/index.stories.js
  src/components/ResponsiveHandler/index.stories.js
  src/components/SelectField/index.stories.js
  src/components/Separator/index.stories.js
  src/components/TextareaField/index.stories.js
  src/components/Tile/index.stories.js
  src/components/TileCaption/index.stories.js
  src/components/TileCheck/index.stories.js
  src/components/TileImage/index.stories.js
  src/components/TileOverlay/index.stories.js
  src/components/TileProgress/index.stories.js
  src/components/TileVideo/index.stories.js
  src/components/ToggleHandler/index.stories.js
  src/components/VideoPlayer/index.stories.js
  src/foundation/grid/index.stories.js
  src/foundation/scale/index.stories.js
  src/foundation/spacing/index.stories.js
  src/foundation/typography/modifiers.stories.js
  src/foundation/typography/sizes.stories.js
  src/foundation/typography/summary.stories.js
  src/foundation/utilities/display.stories.js
  src/foundation/variables/index.stories.js
  src/playground/home/index.stories.js
  src/playground/lihp/index.stories.js
  src/utils/DocHeader.js
  src/utils/SourceLink.js
  src/utils/addon-source-link/index.js
  src/utils/compose.js
  src/utils/withAddons.js
Labels: enhancement

#465 Adding default anchor link styles
  src/styles/body/_body.scss
Labels: maintenance

#469 Fix bug with modal not zindexing above content
  src/styles/components/_modal.scss
Labels: bug

#471 Background - color: dim
  src/components/Background/index.js
  src/components/Background/index.stories.js
  src/styles/components/_background.scss
Labels: enhancement

#472 Removing default background for VideoPlayer screens
  src/components/VideoPlayer/index.stories.js
  src/styles/components/_video-player.scss
Labels: enhancement

#473 Fixing anchor styles on hover
  src/foundation/typography/modifiers.stories.js
  src/styles/typography/_modifiers.scss
Labels: bug
