Repository yankaindustries/mc-components, pull requests merged in 2019-10, with the labels that each got.

#572 Updating LG for responsive handler to be correct value (same as SCSS)
  src/components/ResponsiveHandler/index.js
Labels: bug

#579 Adding three icons
  src/assets/icons/document.svg
  src/assets/icons/lessons.svg
  src/assets/icons/levels.svg
  src/components/Icons/Document.js
  src/components/Icons/Lessons.js
  src/components/Icons/Levels.js
  src/components/Icons/icons.js
Labels: new component

#580 Carousel - Peek Gradient
  src/components/Carousel/index.js
  src/components/Carousel/index.stories.js
  src/styles/components/carousel/_base.scss
  src/styles/components/carousel/_modifiers.scss
Labels: enhancement

#584 Roll back storybook deployer because it wont compile styles
  package.json
  yarn.lock
Labels: maintenance

#586 Disable treeshaking - that was the main issue
  package.json
  yarn.lock
Labels: maintenance

#589 Fixing incorrect TileImage prop
  src/styles/components/_tile.scss
Labels: maintenance

#592 Fixing conflicts Carousel style conflicts
  src/components/Carousel/index.js
  src/styles/components/carousel/_modifiers.scss
Labels: bug

#595 [DNM] adding pointer style if tile has onClick prop set
  src/components/Tile/index.js
  src/styles/components/_tile.scss
Labels: DO-NOT-MERGE

#604 Updating documentation for themes
  src/foundation/utilities/index.stories.js
  src/foundation/utilities/theme.stories.js
Labels: maintenance

#605 Adding icon sizing documentation
  src/components/Icons/index.stories.js
  src/foundation/utilities/theme.stories.js
Labels: maintenance

#606 Updating all assets to be local to storybook
  package.json
  src/components/Carousel/index.stories.js
  src/components/CarouselConnector/index.stories.js
  src/playground/home/index.stories.js
  src/playground/lihp/index.stories.js
  storybook-static/images/in-the-news/bb.svg
  storybook-static/images/in-the-news/espn.svg
  storybook-static/images/in-the-news/nbc.svg
  storybook-static/images/in-the-news/nyt.svg
  storybook-static/images/in-the-news/today.svg
  storybook-static/images/in-the-news/vf.svg
  storybook-static/images/instructors/full-da.jpg
  storybook-static/images/instructors/full-dakr.jpg
  storybook-static/images/instructors/full-dm.jpg
  storybook-static/images/instructors/full-dvf.jpg
  storybook-static/images/instructors/full-gr.jpg
  storybook-static/images/instructors/full-rh.jpg
  storybook-static/images/instructors/full-slj.jpg
  storybook-static/images/instructors/full-sr.jpg
  storybook-static/images/instructors/full-tk.jpg
  storybook-static/images/instructors/full-wh.jpg
  storybook-static/images/instructors/thumb-avb.jpg
  storybook-static/images/instructors/thumb-dm.jpg
  storybook-static/images/instructors/thumb-dvf.jpg
  storybook-static/images/instructors/thumb-mg.jpg
  storybook-static/images/instructors/thumb-rh.jpg
  storybook-static/images/instructors/thumb-slj.jpg
  storybook-static/images/instructors/thumb-sm.jpg
  storybook-static/images/instructors/thumb-sr.jpg
  storybook-static/images/instructors/thumb-tk.jpg
  storybook-static/images/instructors/thumb-wh.jpg
  storybook-static/images/playground/learn-from-the-best.jpg
  storybook-static/images/playground/saying-al.png
  storybook-static/images/playground/saying-gr.png
  storybook-static/images/playground/saying-jp.png
  storybook-static/images/playground/saying-student.png
  storybook-static/images/playground/tile-al.jpeg
  storybook-static/images/playground/tile-aw.jpeg
  storybook-static/images/playground/tile-dn.jpeg
  storybook-static/images/playground/tile-full-mg.jpeg
  storybook-static/images/playground/tile-full-sl.jpeg
  storybook-static/images/playground/tile-ma.jpeg
Labels: maintenance

#607 Updating opacity to 0.6 for muted
  src/styles/helpers/_opacity.scss
Labels: maintenance
