Repository yankaindustries/mc-components, pull requests merged in 2019-08, with the labels that each got.

#531 VideoPlayer - Crop video for non-16x9 player sizes.
  src/components/VideoPlayer/index.js
  src/styles/components/_tile.scss
  src/styles/components/_video-player.scss
Labels: enhancement

#535 Updating letter spacing to match figma
  src/styles/typography/_base.scss
  src/styles/typography/_modifiers.scss
Labels: maintenance

#537 fixing video player class name
  src/styles/components/_video-player.scss
Labels: bug

#541 initial pass at toast render
  src/components/Toast/index.js
  src/components/Toast/index.stories.js
  src/styles/base/_variables.scss
  src/styles/components/_components.scss
  src/styles/components/_toast.scss
Labels: new component

#552 Re-adding assets
  build/assets.js
Labels: bug

#553 Circle CI Update - attempt build
  .circleci/config.yml
Labels: enhancement
