Repository yankaindustries/mc-components, pull requests merged in 2019-09, with the labels that each got.

#554 Add better documentation for the available bootstrap helpers
  src/foundation/grid/index.stories.js
Labels: maintenance

#556 Remove legacy button support
  src/components/Button/index.js
Labels: maintenance

#557 Update icons to actually use the mc-icon class
  src/components/Icons/index.js
  src/styles/components/_icons.scss
Labels: maintenance

#565 Fixing alignment issues with video player
  src/styles/components/_video-player.scss
Labels: bug

#571 Adding D1, D2, and D3 display font-sizes
  src/foundation/typography/sizes.stories.js
  src/foundation/typography/summary.stories.js
  src/styles/typography/_base.scss
Labels: enhancement

#573 Fixing incorrect logo
  src/assets/icons/logo.svg
  src/components/Icons/Logo.js
Labels: bug
