Repository yankaindustries/mc-components, pull requests merged in 2019-05, with the labels that each got.

#476 Adding a rounded class helper and symmetrical icon styles
  src/components/Button/index.js
  src/components/Button/index.stories.js
  src/styles/base/_variables.scss
  src/styles/components/_badge.scss
  src/styles/components/_icons.scss
  src/styles/components/_rounded-box.scss
  src/styles/components/_video-player.scss
  src/styles/components/buttons/_buttons.scss
  src/styles/components/forms/_checkbox.scss
  src/styles/components/forms/_element.scss
  src/styles/helpers/_corners.scss
  src/styles/helpers/_helpers.scss
Labels: enhancement

#479 Dropdown Component
  .storybook/_upside-down.scss
  src/components/Button/index.stories.js
  src/components/ClickOutside/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/index.stories.js
  src/components/DropdownBody/index.js
  src/components/DropdownContent/index.js
  src/components/DropdownFooter/index.js
  src/components/DropdownHeader/index.js
  src/components/DropdownItem/index.js
  src/components/DropdownToggle/index.js
  src/styles/components/_background.scss
  src/styles/components/_components.scss
  src/styles/components/_dropdown.scss
  src/styles/typography/_modifiers.scss
  src/utils/SourceLink.js
Labels: new component

#484 adding bookmarked icon
  src/assets/icons/bookmarked.svg
  src/components/Icons/Bookmarked.js
  src/components/Icons/constants.js
Labels: new component

#485 Tooltip Component
  package.json
  src/components/Button/index.js
  src/components/Tooltip/index.js
  src/components/Tooltip/index.stories.js
  src/components/TooltipBody/index.js
  src/components/TooltipToggle/index.js
  src/styles/components/_components.scss
  src/styles/components/_tooltip.scss
  yarn.lock
Labels: new component

#488 Removing release candidate folder to cleanup cloudfront links
  src/styles/release-candidate/components/_header.scss
  src/styles/release-candidate/components/_mobile-nav-button.scss
  src/styles/release-candidate/components/_navbar-menu.scss
Labels: maintenance

#489 Tooltip - Improvements
  src/components/Tooltip/index.js
Labels: enhancement

#492 Adding the ability for the Button to render another component/element
  src/components/Button/index.js
  src/styles/base/mixins/_ratios.scss
Labels: enhancement

#496 Tooltip - Controlled Component
  src/components/Button/index.js
  src/components/Tooltip/index.js
  src/components/Tooltip/index.stories.js
  src/components/TooltipContent/index.js
  src/components/TooltipContentControlled/index.js
  src/components/TooltipToggle/index.js
  src/components/helpers.js
  src/styles/components/_tooltip.scss
Labels: enhancement, new component

#497 Dropdown - Controlled
  src/components/ClickOutside/index.js
  src/components/Dropdown/index.js
  src/components/Dropdown/index.stories.js
  src/components/DropdownContent/index.js
  src/components/DropdownContentControlled/index.js
  src/components/DropdownItem/index.js
  src/components/DropdownToggle/index.js
  src/components/Tooltip/index.js
  src/components/TooltipContentControlled/index.js
  src/styles/components/_dropdown.scss
Labels: enhancement, new component
