Repository yankaindustries/mc-components, pull requests merged in 2019-02, with the labels that each got.

#362 Fix modal background scroll
  src/components/Modal/index.js
  src/styles/components/_modal.scss
Labels: enhancement

#363 Adding documentation for margin and padding helpers
  src/foundation/spacing/index.stories.js
Labels: maintenance

#364 Modals
  src/components/Modal/index.js
  src/components/Modal/index.stories.js
  src/components/ModalClose/index.js
  src/components/ModalContent/index.js
  src/styles/components/_modal.scss
Labels: enhancement, new component

#366 Documentation update
  .storybook/_upside-down.scss
  src/components/Badge/index.stories.js
  src/components/Footer/index.stories.js
  src/components/Tile/index.stories.js
  src/components/TileCaption/index.stories.js
  src/components/TileCheck/index.stories.js
  src/components/TileImage/index.stories.js
  src/components/TileOverlay/index.stories.js
  src/components/TileVideo/index.js
  src/components/VideoPlayer/index.stories.js
  src/foundation/grid/_styles.css
  src/foundation/grid/index.stories.js
  src/foundation/introduction/getting-started.stories.js
  src/foundation/introduction/index.stories.js
  src/foundation/scale/scale.stories.js
  src/foundation/spacing/index.stories.js
  src/foundation/typography/alignment.stories.js
  src/foundation/typography/flourishes.stories.js
  src/foundation/typography/index.stories.js
  src/foundation/typography/modifiers.stories.js
  src/foundation/typography/sizes.stories.js
  src/foundation/typography/summary.stories.js
  src/playground/home/index.stories.js
  src/playground/typography/index.stories.js
  src/styles/libraries/bootstrap-overrides/_grid.scss
  src/styles/typography/_base.scss
  src/styles/typography/_modifiers.scss
  src/utils/PropExample.js
Labels: maintenance

#371 Updating tertiary button implementation
  src/components/Button/index.stories.js
  src/styles/components/buttons/_button--inverted.scss
  src/styles/components/buttons/_button--types.scss
  src/styles/components/buttons/_button.scss
  src/styles/components/buttons/_buttons.scss
Labels: enhancement

#378 making sure the html font size stays as we set it
  src/styles/base/mixins/_step.scss
  src/styles/typography/_base.scss
Labels: maintenance
